// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lusaekmxjztqfdylpkxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c2Fla214anp0cWZkeWxwa3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjAwMjUsImV4cCI6MjA3NDI5NjAyNX0.bfebbVKTJweXPF9kis3kFiA_a7OD0wUNql7rMIULRFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});